### ISSUE TITLE
CPC: concepts sharing the same prefLabel

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/Code-lists#17]
CPC contains several concepts that share the same preferred label. For example, `<http://data.openbudgets.eu/resource/codelist/cpc/98>`, `<http://data.openbudgets.eu/resource/codelist/cpc/980>`, `<http://data.openbudgets.eu/resource/codelist/cpc/9800>`, and `<http://data.openbudgets.eu/resource/codelist/cpc/98000>` all share the preferred label `"Domestic services"@en`. This is considered to be a bad practice ([see here](https://github.com/cmader/qSKOS/wiki/Quality-Issues#Overlapping_Labels)). Is this issue a problem of the source data or the conversion?

**Comment by skarampatakis** [comment]
As you can see this is a fault of the source codelist itself 

http://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=LST_CLS_DLD&StrNom=CPC_2&StrLanguageCode=EN&StrLayoutCode=HIERARCHIC#

and occurs on multiple codes and some other codelists also. That's because some codes have the same description on multiple levels. 

A possible solution to this could be to concatenate the description with the level so every label would be unique. Or we could leave them as is.

**Comment by pwalsh** [comment]
This is very, very common across budgetary classification in the real world, and is not a "fault" - it is a property of the data itself.

**Comment by skarampatakis** [comment]
I couldn't agree more but also my thought on this is that these structures should be defined better, as this report also recommends

http://ec.europa.eu/internal_market/publicprocurement/docs/rules/cpv/121219_report-review-cpv-codes-functioning_en.pdf

**Comment by pwalsh** [comment]
Well, yeah, the world _should_ be different in many ways :). Until then....

**Comment by jindrichmynarz** [comment]
OK, thanks for the explanation. This might make linking external datasets more ambiguous, because we would need to choose at what level to make a link based on a match on label shared by multiple concepts in the code list's hierarchy.
